version: '3.6'

services:
  restful-booker:
    image: ankurpshah/restful-booker
    ports:
      - "3001:3001"
  test-restful-booker-extra:
    image: ankurpshah/newman-with-htmlextra
    tty: true
    volumes:
      - ${PWD}/collection:/etc/postman
      - ${PWD}/env:/etc/env
      - ${PWD}/report:/etc/report
    command:
      - run
      - /etc/postman/smoke.postman_collection.json
      - --environment
      - /etc/env/docker.postman_environment.json
      - --reporters
      - htmlextra,junit
      - --reporter-htmlextra-export 
      - /etc/report/html/smoke.html
      - --reporter-htmlextra-title 
      - "Smoke Test"
      - --reporter-junit-export
      - /etc/report/junit/smoke-report.xml
